### ISSUE TITLE
Playback issue with version 0.7.4

### ISSUE THREAD

**Issue by tuhin10** [h6ah4i/android-openslmediaplayer#35]
Something's wrong in the latest version, its skipping fast forwding on its own.

**Comment by h6ah4i** [comment]
I have not changed so much since v0.7.2. Maybe that seems NDK r15 related issue, I guess...  Could you give more info that help reproducing the issue?

- Android OS version
- Device / Model

**Comment by tuhin10** [comment]
I am using your sample code only. Its working fine with v0.7.3.

 Android OS version- 6.0.1(Cyanogen Os- 13.1.2)
Device / Model - One Plus One(A0001)

**Comment by anonym24** [comment]
Similar issue for me with 0.7.4 (0.7.3 works fine), when I start playing file, everything is ok, when I press pause button and then again play (to play the same file) it starts playing it fast, then when I change to the next file (next button) it again plays it ok at the first time but after pause the song starts fast
I can even hear that it starts playing fast when I press pause (because with this player pause isn't instant, it has some effect (lowering the volume firstly and then pause, some delay before pause) enabled by default as I understood

My phone: Xiaomi Redmi 4 Prime 6.0.1

**Comment by h6ah4i** [comment]
@tuhin10 @anonym24 Hi. Thanks for your info! I have just released v0.7.5 which fixed this issue.
